### ISSUE TITLE
Mutational Patterns not in import list (not installed with other dependencies)

### ISSUE THREAD

**Issue by jnickfisk** [Townsend-Lab-Yale/cancereffectsizeR#12]

**Comment by jeff-mandell** [comment]
It's in Suggests because it's possible to run a cancereffectsizeR analysis without it if you use the alternative signature extractor, deconstuctSigs. There's supposed to be an informative message to install the package if it's needed and not installed. Did you run into a situation where that didn't happen?

**Comment by jnickfisk** [comment]
I am, as they say, a dingus
